Fix_to_model_filename. (#167)
* Fix `uninitialized constant NestedForm::BuilderMixin (NameError)`.

* Targeted for actions when pushing to the main branch.

* Fix to import the assets of webpacker on production.

* Made test data static due to incorrect characters

* Work to sidekiq-scheduler.

* View all field for contents models

* Fix to work api.

* Fixe to the argument errors.

* Prepared a toggle button to enable Google Translate.

* Fix to model filename.

* Fix to typo.

* Fix to 'undefined method `value`'.